# Generated by Django 4.2.30 on 2026-06-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("client_name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/covers/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-completion_date", "-created_at"],
            },
        ),
    ]
