# Generated by Django 4.2.30 on 2026-06-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="icon_name",
            field=models.CharField(
                blank=True, help_text="Lucide icon name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="short_info",
            field=models.CharField(
                blank=True,
                help_text="Small tagline for the project card",
                max_length=255,
            ),
        ),
    ]
