# Generated by Django 4.2.30 on 2026-06-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="title",
            new_name="role",
        ),
        migrations.RemoveField(
            model_name="education",
            name="completion_date",
        ),
        migrations.AddField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(default="Computer Science", max_length=100),
        ),
        migrations.AddField(
            model_name="education",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
