# Generated by Django 4.2.30 on 2026-06-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_rename_title_experience_role_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutprofile",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["-end_date"]},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["category", "name"]},
        ),
    ]
