# Generated by Django 4.2.30 on 2026-06-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_alter_aboutprofile_options_alter_education_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="focus_area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("model_layer", "Model Layer"),
                    ("agent_framework", "Agent Framework"),
                    ("tool_context_layer", "Tool/Context Layer"),
                    ("memory_retrieval", "Memory & Retrieval"),
                    ("orchestration", "Orchestration"),
                    ("eval_observability", "Eval & Observability"),
                    ("serving_infra", "Serving & Infra"),
                    ("guardrails", "Guardrails"),
                    ("data_state", "Data/State"),
                ],
                max_length=30,
            ),
        ),
    ]
