# Generated by Django 6.1 on 2026-08-28 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('category', models.CharField(choices=[('room', 'Room Features'), ('view', 'Views'), ('service', 'Services'), ('accessibility', 'Accessibility')], default='room', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('interests', models.CharField(blank=True, help_text='Comma-separated: romantic, budget, luxury, honeymoon, etc.', max_length=200)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(blank=True, max_length=100)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OccasionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#4A6FA5', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('description', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='states/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'States',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('is_jacuzzi_verified', models.BooleanField(default=False, help_text='Confirmed in-room jacuzzi/hot tub')),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Details about jacuzzi type, location in room, etc.')),
                ('price_from', models.DecimalField(decimal_places=2, help_text='Starting price per night', max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price_last_updated', models.DateTimeField(blank=True, null=True)),
                ('guest_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average guest rating (0-5)', max_digits=3, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('booking_com_link', models.URLField(blank=True, help_text='Booking.com affiliate link')),
                ('expedia_link', models.URLField(blank=True, help_text='Expedia affiliate link')),
                ('direct_link', models.URLField(blank=True, help_text='Direct hotel booking link')),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('primary_keyword', models.CharField(blank=True, max_length=100)),
                ('secondary_keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured listings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='hotels', to='hotels.amenity')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotels.city')),
                ('occasions', models.ManyToManyField(blank=True, related_name='hotels', to='hotels.occasiontag')),
            ],
            options={
                'ordering': ['-is_featured', '-guest_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_hero', models.BooleanField(default=False, help_text='Use as primary/hero image')),
                ('shows_jacuzzi', models.BooleanField(default=False, help_text='Image clearly shows in-room jacuzzi')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
            options={
                'ordering': ['order', '-is_hero'],
            },
        ),
        migrations.CreateModel(
            name='HotelSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_name', models.CharField(max_length=100)),
                ('submitter_email', models.EmailField(max_length=254)),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_address', models.CharField(max_length=255)),
                ('hotel_city', models.CharField(max_length=100)),
                ('hotel_state', models.CharField(max_length=2)),
                ('hotel_zip', models.CharField(max_length=10)),
                ('hotel_website', models.URLField(blank=True)),
                ('hotel_phone', models.CharField(blank=True, max_length=20)),
                ('jacuzzi_type', models.CharField(choices=[('in_room', 'In-Room Jacuzzi'), ('private_outdoor', 'Private Outdoor Hot Tub'), ('shared_spa', 'Shared Spa Facility'), ('not_sure', 'Not Sure')], max_length=50)),
                ('jacuzzi_description', models.TextField()),
                ('has_photos', models.BooleanField(default=False)),
                ('price_range', models.CharField(blank=True, max_length=50)),
                ('occasion_visited', models.CharField(blank=True, max_length=100)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs More Information')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='hotels.state'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for listings')),
                ('content', models.TextField(help_text='Full blog post content (HTML/Markdown)')),
                ('category', models.CharField(choices=[('destination', 'Destination Guide'), ('occasion', 'Occasion-Based'), ('amenity', 'Amenity Focus'), ('brand', 'Hotel Brand'), ('budget', 'Budget/Luxury'), ('tips', 'Travel Tips')], default='destination', max_length=50)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags')),
                ('primary_keyword', models.CharField(max_length=100)),
                ('secondary_keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('featured_image_alt', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('reading_time', models.CharField(default='5 min read', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('schema_type', models.CharField(choices=[('Article', 'Article'), ('FAQPage', 'FAQ Page')], default='Article', max_length=20)),
                ('faq_data', models.JSONField(blank=True, help_text='FAQ schema data as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_blog_posts', to=settings.AUTH_USER_MODEL)),
                ('related_hotels', models.ManyToManyField(blank=True, related_name='related_blog_posts', to='hotels.hotel')),
                ('related_states', models.ManyToManyField(blank=True, related_name='related_blog_posts', to='hotels.state')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='verifications/')),
                ('photo_type', models.CharField(choices=[('jacuzzi_closeup', 'Jacuzzi Close-up'), ('room_context', 'Jacuzzi in Room Context'), ('bathroom_overall', 'Overall Bathroom'), ('amenity_detail', 'Amenity Detail')], max_length=20)),
                ('caption', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_photos', to='hotels.hotel')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['is_featured', '-guest_rating'], name='hotels_hote_is_feat_59abcf_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city', 'is_active'], name='hotels_hote_city_id_fb7985_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'slug')},
        ),
    ]
