# Generated by Django 4.2.30 on 2026-06-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.TextField(blank=True)),
                ("cta_primary_text", models.CharField(blank=True, max_length=50)),
                ("cta_primary_link", models.CharField(blank=True, max_length=255)),
                ("cta_secondary_text", models.CharField(blank=True, max_length=50)),
                ("cta_secondary_link", models.CharField(blank=True, max_length=255)),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="home/hero/"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to True to make this the active hero.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
