# Generated by Django 4.2.30 on 2026-06-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BioSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Bio Info", max_length=255)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="JourneyPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["phase_number"],
            },
        ),
        migrations.RenameField(
            model_name="herosection",
            old_name="subtitle",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="herosection",
            old_name="background_image",
            new_name="hero_image",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="cta_secondary_link",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="cta_secondary_text",
        ),
        migrations.AddField(
            model_name="herosection",
            name="role_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="herosection",
            name="tech_stack",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of tech stack items"
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
