# Generated by Django 4.2.30 on 2026-06-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_biosection_journeyphase_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="herosection",
            old_name="cta_primary_link",
            new_name="protocol_link",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="cta_primary_text",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="role_title",
        ),
        migrations.AddField(
            model_name="herosection",
            name="architecture_link",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="herosection",
            name="architecture_text",
            field=models.CharField(default="VIEW ARCHITECTURE", max_length=50),
        ),
        migrations.AddField(
            model_name="herosection",
            name="protocol_text",
            field=models.CharField(default="INITIALIZE PROTOCOL", max_length=50),
        ),
        migrations.AddField(
            model_name="herosection",
            name="system_status",
            field=models.CharField(default="SYSTEM ARCHITECTURE READY", max_length=100),
        ),
        migrations.AddField(
            model_name="herosection",
            name="title_accent",
            field=models.CharField(
                blank=True,
                help_text="The accent part of the title (e.g. 'Engineer Architect')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="tech_stack",
            field=models.TextField(
                blank=True, help_text="Comma-separated items for the marquee bar"
            ),
        ),
    ]
