# Generated by Django 4.2.30 on 2026-06-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_cta_primary_link_herosection_protocol_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="biosection",
            name="icon",
            field=models.CharField(
                blank=True, help_text="Lucide icon name or SVG path", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="biosection",
            name="subtitle",
            field=models.CharField(default="Info", max_length=255),
        ),
        migrations.AddField(
            model_name="journeyphase",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="biosection",
            name="title",
            field=models.CharField(default="Bio", max_length=255),
        ),
    ]
