# Generated by Django 6.0.5 on 2026-06-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_specs',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'Model Core': 'GPT-4', 'Latency': '150ms'}"),
        ),
    ]
