# Generated by Django 4.2.30 on 2026-06-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Architecting Autonomous Intelligence", max_length=200
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="The Future of Agentic AI Engineering", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="A comprehensive knowledge hub and portfolio dedicated to production-grade Agentic AI systems."
                    ),
                ),
                (
                    "primary_cta_text",
                    models.CharField(default="Explore Domains", max_length=50),
                ),
                (
                    "primary_cta_link",
                    models.CharField(default="/knowledge", max_length=200),
                ),
                (
                    "secondary_cta_text",
                    models.CharField(default="View Projects", max_length=50),
                ),
                (
                    "secondary_cta_link",
                    models.CharField(default="/projects", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Hero Content",
            },
        ),
        migrations.CreateModel(
            name="StatCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=20)),
                ("icon", models.CharField(help_text="Lucide icon name", max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
