# Generated by Django 4.2.30 on 2026-06-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Homepage"),
                            ("about", "About Page"),
                            ("projects", "Projects Page"),
                            ("blog", "Blog Page"),
                            ("knowledge", "Knowledge Hub"),
                            ("contact", "Contact Page"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "endpoint",
                    models.CharField(
                        help_text="Local API path (e.g., about/awards/)", max_length=255
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        default="generic",
                        help_text="Component to use (e.g., hero, grid, stats, generic)",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
