# Generated by Django 4.2.30 on 2026-06-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_pagesection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="herocontent",
            options={
                "ordering": ["-updated_at"],
                "verbose_name_plural": "Hero Content",
            },
        ),
    ]
