# Generated by Django 4.2.30 on 2026-06-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_alter_herocontent_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Homepage"),
                            ("about", "About Page"),
                            ("projects", "Projects Page"),
                            ("blog", "Blog Page"),
                            ("knowledge", "Knowledge Hub"),
                            ("contact", "Contact Page"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("badge", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("highlighted_word", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Page Headers",
            },
        ),
    ]
