# Generated by Django 4.2.30 on 2026-06-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reading_time",
            field=models.CharField(default="10 min read", max_length=50),
        ),
    ]
