# Generated by Django 6.0.5 on 2026-06-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'Throughput': 'High', 'Latency': 'Low'}"),
        ),
    ]
